// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.app.android) apply false
    alias(libs.plugins.app.google.services) apply false
    alias(libs.plugins.app.hilt) apply false
    alias(libs.plugins.app.secrets) apply false
}
