plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.example.homeelecation'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.homeelecation"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

        //
        namespace 'com.example.homeelecation'
        buildToolsVersion '33.0.0'
        dependenciesInfo {
            includeInApk true
            includeInBundle true
        }
        //
    }
    buildFeatures {
        viewBinding true
    }
}



dependencies {


        // Import the BoM for the Firebase platform
        implementation(platform('com.google.firebase:firebase-bom:33.1.1'))
    implementation("com.google.firebase:firebase-auth")

        // Add the dependencies for the App Check libraries
        // When using the BoM, you don't specify versions in Firebase library dependencies
            implementation('com.google.firebase:firebase-appcheck-playintegrity:18.0.0')


        // Add the dependencies for the In-App Messaging and Analytics libraries
        // When using the BoM, you don't specify versions in Firebase library dependencies
       // implementation("com.google.firebase:firebase-inappmessaging-display")
        implementation("com.google.firebase:firebase-analytics")


    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.firebase:firebase-auth:23.0.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.2'
    implementation 'androidx.navigation:navigation-fragment:2.7.7'
    implementation 'androidx.navigation:navigation-ui:2.7.7'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'com.google.firebase:firebase-firestore:25.0.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    // browser
    implementation 'androidx.browser:browser:1.8.0'

    //duplicated class
    implementation(platform('org.jetbrains.kotlin:kotlin-bom:2.0.0'))

//rounded imageview
    implementation 'com.makeramen:roundedimageview:2.3.0'
    //rounded imageview

    ///glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    ///glide

    ///circleImage
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    ///circleImage

    ///razorpay payment
    implementation 'com.razorpay:checkout:1.6.39'
    ///razorpay payment
}